### PR TITLE
Make regex work on null-containing strings

### PR DESCRIPTION
**Pull request by csarn**
To allow forwarding to different ssl-enabled webservers depending on hostname, I create a copy of the protocol data in which all null bytes are replaced by 0xff, and run the regex against that copy.

I understand that this is some kind of hack, so feel free to disregard this pull request, but maybe other users are also interested in this?

To clarify, this is my specific use case:
I'm running an instance of gitlab on my server, but also other web services. I want all of them to be ssl-protected. Having one reverse ssl proxy dispatching between gitlab and the other services would be hard to do, as I would have to run gitlab without ssl, but still announce its own url using "https://". So this sslh hack is my solution.

### CODE REVIEW

**Comment by yrutschle** [comment]
On Sat, Dec 10, 2016 at 11:48:37AM -0800, Christoph Sarnowski wrote:
> To allow forwarding to different ssl-enabled webservers depending on hostname, I create a copy of the protocol data in which all null bytes are replaced by 0xff, and run the regex against that copy.
> 
> I understand that this is some kind of hack, so feel free to disregard this pull request, but maybe other users are also interested in this?

I may be confused, but it sounds like what you're doing is
what SNI is made for.

Y.

**Comment by csarn** [comment]
Ok, I did not know what that is, but it seems like what I want. Thanks!
Now I need to chain sniproxy between webservices and sslh, but thats better than maintaining an ugly patch trying to do sniproxys job.

I'll close this then.

**Comment by yrutschle** [comment]
I thought I answered this but I can't see my own comment... Here it is again: sniproxy's functionality is largely present in sslh as well, you can switch protocols based on SNI and ALPN straight from sslh. Refer to example.cfg.

**Comment by csarn** [comment]
Oh, I see... but only in 1.18, right (judging from example.cfg)? When you pointed me towards the SNI thing, I thought I could then stay with my distro's sslh package. Debian jessie only ships 1.16, so I'll need to use a backport.

**Comment by yrutschle** [comment]
Sorry, I have no idea what sslh is included in Debian, I
tend to run my own version that's the head on Git :-)

On the other hand, if sniproxy isn't part of Debian, you end
having to download and compile something either way.

**Comment by csarn** [comment]
Yes, this is why I switched to pure sslh 1.18 now. Installing sslh 1.18 from debian testing was no trouble.
:-)

**Pull request closed without merging**
