### PR TITLE
Add built-in MSRDP support; exclude 

### PR DESCRIPTION
**Pull request by akappner**
Add built-in detection for Microsoft Remote Desktop Protocol. The detection routine is based off the tpkt_read_header function in the libfreerdp project. 

Also add echosrv-conf.c and echosrv-conf.h to gitexclude, as these files are build artifacts that should not be in the repo.

### CODE REVIEW

**Comment by yrutschle** [comment]
can you remove the gitignore part? I'd prefer having those files in git to not force people to have a working conf2struct to build sslh

**Comment by akappner** [comment]
> can you remove the gitignore part? I'd prefer having those files in git to not force people to have a working conf2struct to build sslh

Thanks for reviewing -- revised it accordingly.

**Comment by yrutschle** [comment]
Apologies, I somehow lost your name on the commit while solving conflicts in the merge. I'll add your name to the ChangeLog, anyways.

**Comment by yrutschle** [comment]
and thanks for the contribution :-)

**Pull request closed without merging**
