### PR TITLE
Added some example regex for UDP forward.

### PR DESCRIPTION
**Pull request by lnslbrty**
As part of #279, here are some regexes that are well tested and work.
(might be helpful for others that may not read github issues)

### CODE REVIEW

**Comment by yrutschle** [comment]
Thanks!

I'll merge right away, but I'll try and write a hardcoded probe for these.

for my information, do you get the pattern at the beginning of the packets, or at some higher offset? (meaning: if you matched "^\x51\x30\x35\x30", would it still work?)

**Comment by lnslbrty** [comment]
There is a byte between `^` and `\x51\x30\x35\x30`. The following regex may also work: `^.?\x51\x30\x35\x30`.

**Comment by yrutschle** [comment]
Out of curiosity, is there any reason you write the regex as hex insteadof simply ^.Q050 ?

FYI, I pushed hardcoded probes which match the patterns you identified, which I expect should be way faster than regexes. I'm yet to add test code for UDP probes.

**Comment by lnslbrty** [comment]
> Out of curiosity, is there any reason you write the regex as hex insteadof simply ^.Q050 ?

The QUIC version protocol field is not a string. Facebook uses `0xfaceb002` for example.
Which variant makes more sense is a matter of opinion, I think.

**Comment by yrutschle** [comment]
Oh right. That makes the hardcoded probe sort of useless then I guess, unless we make the version a parameter to the probe.

**Comment by yrutschle** [comment]
I just ran a small benchmark to compare PCRE2 with trivial regex versus memmem(), and it turns out they're comparable (who said "don't optimise prematurely"?)

Now I'm thinking I might add preset, regex-based probes ("quick50 is a regex probe that succeeds if it matches /Q050/"). Either way, I'll probably remove the hardcoded probe as it's bound to cause confusion among people who don't know enough about QUIC versions, and do a version release before doing that work.

**Comment by lnslbrty** [comment]
Performance might be even better with Intel's `hyperscan`. But probably not required for most use-cases.

**Pull request merged**
