### PR TITLE
tls: proposed fix for incorrect SNI/ALPN matching

### PR DESCRIPTION
**Pull request by rom1dep**
follow-up of issue #197

### CODE REVIEW

**Comment by yrutschle** [comment]
Thanks -- I want to set up test cases for ALPN/SNI before merging this though (that'll increase my confidence that I'm testing the right things :) ).

**Comment by rom1dep** [comment]
I could help with that, but I can't even run the test suite. Any idea what the requirements would be on a recent fedora?

**Comment by yrutschle** [comment]
I guess you might be missing Perl's Conf::Libconfig module, which you'd install as such:
```
cpan Conf::Libconfig
```
Everything else is part of the Perl core distribution if I'm not mistaken.
I'm looking into it right now, so I'm hoping I'll be done in a few days (my time is very fragmented at the moment)

**Comment by yrutschle** [comment]
Ok, testing is in place, and your fix is confirmed to work. Thanks!

**Pull request merged**
